name: Comms CI

on:
  pull_request:
    branches: [master]
    types:
      - ready_for_review
      - synchronize

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20'

        - name: Install dependencies
          working-directory: Comms-Client
          run: npm ci
        
        - name: Build
          working-directory: Comms-Client
          run: npm run build

        - name: Run frontend tests
          working-directory: Comms-Client
          run: npm test-ci

        - name: Upload test results
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: frontend-test-results
            path: "test-results/frontend-test-results.xml"



  backend:
    name: Backend CI
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore packages
        run: dotnet restore
        working-directory: Comms-Server

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: Comms-Server

      - name: Verify code style
        run: dotnet format --verify-no-changes --exclude "**/Migrations/**"
        working-directory: Comms-Server

      - name: Run backend tests
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"
        working-directory: Comms-Server

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: "TestResults/backend-test-results.trx"
